export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const RECEIVE_USER = 'RECEIVE_USER'
export const FETCH_BUILDS = 'FETCH_BUILDS';